"""Table init

Revision ID: 0840dd23d9bb
Revises: 
Create Date: 2025-12-08 11:38:47.971453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0840dd23d9bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('warn_height', sa.Float(), nullable=False),
    sa.Column('default_timeout', sa.Integer(), nullable=False),
    sa.Column('logs_moderation', sa.BigInteger(), nullable=True),
    sa.Column('logs_server', sa.BigInteger(), nullable=True),
    sa.Column('rules_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('rules_message_id', sa.JSON(), nullable=True),
    sa.Column('report_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_ticket_type_id', sa.BigInteger(), nullable=True),
    sa.Column('verified_role_id', sa.BigInteger(), nullable=True),
    sa.Column('student_role_id', sa.BigInteger(), nullable=True),
    sa.Column('alumni_role_id', sa.BigInteger(), nullable=True),
    sa.Column('external_role_id', sa.BigInteger(), nullable=True),
    sa.Column('teacher_role_id', sa.BigInteger(), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('new_member_verification_time_limit', sa.Integer(), nullable=False),
    sa.Column('allowed_email_domains', sa.JSON(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['verification_ticket_type_id'], ['ticket_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('embed_color', sa.Integer(), nullable=False),
    sa.Column('ticket_channel_category_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('requires_initial_reason', sa.Boolean(), nullable=False),
    sa.Column('moderator_role_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_ticket_types_guild_id'), 'ticket_types', ['guild_id'], unique=False)
    op.create_table('embeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('footer_text', sa.String(length=2048), nullable=True),
    sa.Column('footer_icon_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('provider_name', sa.String(length=256), nullable=True),
    sa.Column('provider_url', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=256), nullable=True),
    sa.Column('author_url', sa.Text(), nullable=True),
    sa.Column('author_icon_url', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_embeds_guild_id'), 'embeds', ['guild_id'], unique=False)
    op.create_table('gravity_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_gravity_levels_guild_id'), 'gravity_levels', ['guild_id'], unique=False)
    op.create_table('guild_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('rules', sa.String(length=1024), nullable=False),
    sa.Column('rules_require_publish', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_guild_rules_guild_id'), 'guild_rules', ['guild_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('log_type', sa.Enum('infraction_warn', 'infraction_timeout', 'infraction_kick', 'infraction_ban', 'verification_manual', 'unknown', name='logentrytype'), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_logs_actor_id'), 'logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_logs_guild_id'), 'logs', ['guild_id'], unique=False)
    op.create_index(op.f('ix_logs_log_type'), 'logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_logs_target_id'), 'logs', ['target_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('report_reason', sa.String(length=512), nullable=False),
    sa.Column('offender_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('reported_channel_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('reported_message_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('log_message_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'HANDLED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('handler_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('handler_action', sa.Enum('none', 'deleted', 'warned', 'timeout', name='reportaction'), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_message_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_report_guild_id'), 'report', ['guild_id'], unique=False)
    op.create_table('role_panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('multiple_choose', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_role_panels_guild_id'), 'role_panels', ['guild_id'], unique=False)
    op.create_table('ticket_panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_type_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_ticket_panels_channel_id'), 'ticket_panels', ['channel_id'], unique=False)
    op.create_index(op.f('ix_ticket_panels_message_id'), 'ticket_panels', ['message_id'], unique=True)
    op.create_index(op.f('ix_ticket_panels_ticket_type_id'), 'ticket_panels', ['ticket_type_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_type_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('member_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('panel_message_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('handler_id', sa.BigInteger(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_message_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_tickets_channel_id'), 'tickets', ['channel_id'], unique=True)
    op.create_index(op.f('ix_tickets_member_id'), 'tickets', ['member_id'], unique=False)
    op.create_table('embed_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('embed_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('inline', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['embed_id'], ['embeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_embed_fields_embed_id'), 'embed_fields', ['embed_id'], unique=False)
    op.create_table('infractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('infraction_type', sa.Enum('warn', 'timeout', 'kick', 'ban', name='infractiontype'), nullable=False),
    sa.Column('gravity_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('infraction_result', sa.Enum('warn', 'timeout', 'kick', 'ban', 'none', name='infractionresult'), nullable=False),
    sa.Column('timeout_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gravity_id'], ['gravity_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_infractions_guild_id'), 'infractions', ['guild_id'], unique=False)
    op.create_table('role_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['role_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_role_options_panel_id'), 'role_options', ['panel_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('stickers_json', sa.JSON(), nullable=True),
    sa.Column('poll_json', sa.JSON(), nullable=True),
    sa.Column('reference_json', sa.JSON(), nullable=True),
    sa.Column('embeds_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id'),
    sqlite_autoincrement=True
    )
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('pending_email', 'pending_manual', 'pending_reverification', 'expired', 'kicked', 'verified_student', 'verified_alumni', 'verified_external', 'verified_teacher', name='verificationstatus'), nullable=False),
    sa.Column('hashed_code', sa.Text(), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_date', sa.Date(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_guild_user'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_verifications_code_expires_at'), 'verifications', ['code_expires_at'], unique=False)
    op.create_index(op.f('ix_verifications_guild_id'), 'verifications', ['guild_id'], unique=False)
    op.create_index(op.f('ix_verifications_joined_at'), 'verifications', ['joined_at'], unique=False)
    op.create_index(op.f('ix_verifications_user_email'), 'verifications', ['user_email'], unique=False)
    op.create_index(op.f('ix_verifications_user_id'), 'verifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_verifications_verification_expires_at'), 'verifications', ['verification_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_verification_expires_at'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_user_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_user_email'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_joined_at'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_guild_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_code_expires_at'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_role_options_panel_id'), table_name='role_options')
    op.drop_table('role_options')
    op.drop_index(op.f('ix_infractions_guild_id'), table_name='infractions')
    op.drop_table('infractions')
    op.drop_index(op.f('ix_embed_fields_embed_id'), table_name='embed_fields')
    op.drop_table('embed_fields')
    op.drop_index(op.f('ix_tickets_member_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_channel_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_ticket_panels_ticket_type_id'), table_name='ticket_panels')
    op.drop_index(op.f('ix_ticket_panels_message_id'), table_name='ticket_panels')
    op.drop_index(op.f('ix_ticket_panels_channel_id'), table_name='ticket_panels')
    op.drop_table('ticket_panels')
    op.drop_index(op.f('ix_role_panels_guild_id'), table_name='role_panels')
    op.drop_table('role_panels')
    op.drop_index(op.f('ix_report_guild_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_logs_target_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_log_type'), table_name='logs')
    op.drop_index(op.f('ix_logs_guild_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_actor_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_guild_rules_guild_id'), table_name='guild_rules')
    op.drop_table('guild_rules')
    op.drop_index(op.f('ix_gravity_levels_guild_id'), table_name='gravity_levels')
    op.drop_table('gravity_levels')
    op.drop_index(op.f('ix_embeds_guild_id'), table_name='embeds')
    op.drop_table('embeds')
    op.drop_index(op.f('ix_ticket_types_guild_id'), table_name='ticket_types')
    op.drop_table('ticket_types')
    op.drop_table('guilds')
    # ### end Alembic commands ###
