"""Modify LogEntryType values

Revision ID: bd74211255e7
Revises: 0840dd23d9bb
Create Date: 2025-12-15 14:28:17.976936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bd74211255e7'
down_revision: Union[str, Sequence[str], None] = '0840dd23d9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'log_type',
                    existing_type=sa.Enum('infraction_warn', 'infraction_timeout', 'infraction_kick', 'infraction_ban',
                                          'verification_manual', 'unknown', name='logentrytype'),
                    type_=sa.Enum('infraction_warn', 'infraction_timeout', 'infraction_kick', 'infraction_ban',
                                  'verification_manual', 'verification_expired', 'unknown', name='logentrytype'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'log_type',
                    existing_type=sa.Enum('infraction_warn', 'infraction_timeout', 'infraction_kick', 'infraction_ban',
                                          'verification_manual', 'verification_expired', 'unknown',
                                          name='logentrytype'),
                    type_=sa.Enum('infraction_warn', 'infraction_timeout', 'infraction_kick', 'infraction_ban',
                                  'verification_manual', 'unknown', name='logentrytype'),
                    existing_nullable=False)
    # ### end Alembic commands ###
